### ISSUE TITLE
perlInc doesn't add to include path

### ISSUE THREAD

**Issue by willt** [richterger/Perl-LanguageServer#1]
Doesn't seem like adding paths to perlInc in settings has any effect. Also are paths configurable on a perl workspace basis?

`{
    "perl.perlInc": [
        "/home/willt/perl5/lib/perl5",
        "./lib"
    ]
}`

**Comment by richterger** [comment]
Hi,



perl.perlInc work perfectly form me. I use it in my daily work, but please 
use absolute paths instead of the relative one.



Also you can add it to your workspace configuration.



If you look in the output window of the PerlLanguageServer you should see 
that the include paths get added, e.g.:



method=_rpcnot_didChangeConfiguration

path_map = [["file:///", "file:///home/systems/sma71a/"]]

perlinc = [

  "/usr/x/test/lib",

  "/usr/x/master/lib",

]





Regards



Gerald





Von: William Taylor [mailto:notifications@github.com]
Gesendet: Freitag, 31. Mai 2019 00:23
An: richterger/Perl-LanguageServer <Perl-LanguageServer@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [richterger/Perl-LanguageServer] perlInc doesn't add to include 
path (#1)



Doesn't seem like adding paths to perlInc in settings has any effect. Also 
are paths configurable on a perl workspace basis?

{ "perl.perlInc": [ "/home/willt/perl5/lib/perl5", "./lib" ] }

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub 
<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Frichterger%2FPerl-LanguageServer%2Fissues%2F1%3Femail_source%3Dnotifications%26email_token%3DAAS25Z46JZFTHVLXSNGY5V3PYBHTPA5CNFSM4HRMZYIKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GW2SU6Q&e=52cce4d1&h=f1b5849a&f=y&p=y> 
, or mute the thread 
<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAS25ZZVZM3AJMP6QOUXF33PYBHTPANCNFSM4HRMZYIA&e=52cce4d1&h=d67631ab&f=y&p=y> 
.


-- 
This message has been checked by Libra Esva and is found to be clean.
Mark it as spam 
<http://srvmailgw3.i.ecos.de/cgi-bin/learn-msg.cgi?id=85ED84008A.AEBE3>
Blacklist sender 
<http://srvmailgw3.i.ecos.de/cgi-bin/learn-msg.cgi?blacklist=1&id=85ED84008A.AEBE3>

**Comment by willt** [comment]
Are we using the same version? I'm using version 0.9.0.
What output window are you talking about? I don't see anything like that.

I get this error
`[Error - 8:33:04 AM] Connection to server is erroring. Shutting down server.
[Error - 8:33:04 AM] Connection to server is erroring. Shutting down server.
Can't locate Perl/LanguageServer.pm in @INC (you may need to install the Perl::LanguageServer module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base).
BEGIN failed--compilation aborted.`
In settings.json I have
`{
    "perl.perlInc": [
        "/home/wilt/perl5/lib/perl5",
    ]
}`
LanguageServer is here:
`/home/willt/perl5/lib/perl5/Perl/LanguageServer.pm`

**Comment by willt** [comment]
Also where in the code are you using perlInc ?
`grep -R perlInc .
./package.json:				"perl.perlInc": {
./README.md:* `perl.perlInc`: array with paths to add to perl library path
`

**Comment by richterger** [comment]
Just read the error message: “(you may need to install the 
Perl::LanguageServer module)”



Install Perl::LanguageServer (i.e. cpan Perl::LanguageServer), then it 
should work



Regards



Gerald





Von: William Taylor [mailto:notifications@github.com]
Gesendet: Freitag, 31. Mai 2019 17:39
An: richterger/Perl-LanguageServer <Perl-LanguageServer@noreply.github.com>
Cc: Gerald Richter <gerald.richter@ecos.de>; Comment 
<comment@noreply.github.com>
Betreff: Re: [richterger/Perl-LanguageServer] perlInc doesn't add to include 
path (#1)



Are we using the same version? I'm using version 0.9.0.
What output window are you talking about? I don't see anything like that.

I get this error
[Error - 8:33:04 AM] Connection to server is erroring. Shutting down server. 
[Error - 8:33:04 AM] Connection to server is erroring. Shutting down server. 
Can't locate Perl/LanguageServer.pm in @INC (you may need to install the 
Perl::LanguageServer module) (@INC contains: /etc/perl 
/usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 
/usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 
/usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 
/usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base). BEGIN 
failed--compilation aborted.
In settings.json I have
{ "perl.perlInc": [ "/home/wilt/perl5/lib/perl5", ] }
LanguageServer is here:
/home/willt/perl5/lib/perl5/Perl/LanguageServer.pm

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub 
<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Frichterger%2FPerl-LanguageServer%2Fissues%2F1%3Femail_source%3Dnotifications%26email_token%3DAAS25Z7TADIE6J3YMQGQCHLPYFBCNA5CNFSM4HRMZYIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWVSSCQ%23issuecomment-497756426&e=52cce4d1&h=f791bddb&f=y&p=y> 
, or mute the thread 
<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAS25ZY5IT73LVN7PZNWO2DPYFBCNANCNFSM4HRMZYIA&e=52cce4d1&h=80b92822&f=y&p=y> 
.


-- 
This message has been checked by Libra Esva and is found to be clean.
Mark it as spam 
<http://srvmailgw3.i.ecos.de/cgi-bin/learn-msg.cgi?id=0B1A44008A.AEE43>
Blacklist sender 
<http://srvmailgw3.i.ecos.de/cgi-bin/learn-msg.cgi?blacklist=1&id=0B1A44008A.AEE43>

**Comment by willt** [comment]
It is installed.
LanguageServer is here: /home/willt/perl5/lib/perl5/Perl/LanguageServer.pm
The incDir stuff isn't working. I don't even see where you are calling it in your code. Are you sure you aren't working off a newer unreleased version?

If I load module from shell its finds it fine with path:
` perl -I/home/willt/perl5/lib/perl5 -MPerl::LanguageServer -e 'print "VERSION IS: " . $Perl::LanguageServer::VERSION'
VERSION IS: 0.9
`

**Comment by richterger** [comment]
perlInc is for finding modules during syntax checking, not for finding 
Perl::LanguageServer itself.



Unfortunately there is no config option for doing what you want to do, but 
you can create a small script



#!bin/sh



perl -I/home/willt/perl5/lib/perl5 "$@"



and specify it’s name as perl.perlCmd, that should work



Regards



Gerald





Von: William Taylor [mailto:notifications@github.com]
Gesendet: Freitag, 31. Mai 2019 21:06
An: richterger/Perl-LanguageServer <Perl-LanguageServer@noreply.github.com>
Cc: Gerald Richter <gerald.richter@ecos.de>; Comment 
<comment@noreply.github.com>
Betreff: Re: [richterger/Perl-LanguageServer] perlInc doesn't add to include 
path (#1)



It is installed.
LanguageServer is here: /home/willt/perl5/lib/perl5/Perl/LanguageServer.pm
The incDir stuff isn't working. I don't even see where you are calling it in 
your code. Are you sure you aren't working off a newer unreleased version?

If I load module from shell its finds it fine with path:
perl -I/home/willt/perl5/lib/perl5 -MPerl::LanguageServer -e 'print "VERSION 
IS: " . $Perl::LanguageServer::VERSION' VERSION IS: 0.9

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub 
<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Frichterger%2FPerl-LanguageServer%2Fissues%2F1%3Femail_source%3Dnotifications%26email_token%3DAAS25Z5EB63WGBG7NLUIQEDPYFZIJA5CNFSM4HRMZYIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWWDXAY%23issuecomment-497826691&e=52cce4d1&h=62c8a2ac&f=y&p=y> 
, or mute the thread 
<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAS25Z757OMG5224X5XEOPDPYFZIJANCNFSM4HRMZYIA&e=52cce4d1&h=a9705899&f=y&p=y> 
.


-- 
This message has been checked by Libra Esva and is found to be clean.
Mark it as spam 
<http://srvmailgw3.i.ecos.de/cgi-bin/learn-msg.cgi?id=842DF4008A.AD8AC>
Blacklist sender 
<http://srvmailgw3.i.ecos.de/cgi-bin/learn-msg.cgi?blacklist=1&id=842DF4008A.AD8AC>

**Comment by willt** [comment]
Awesome that worked great. Make sense.
Now I release that perlInc gets pulled in by Perl::LanguageServer.
Thanks!

**Comment by nicomen** [comment]
Does not make sense to me. But I just figured out myself just before finding this. Could you perhaps add a note in the extension description?

Oh, and I added the locallib path to find Perl::LanguageServer in .bash_profile rather than using a workaround wrapper. (.bashrc is not executed it seems)
