### ISSUE TITLE
Getting "couldn't start client Perl Language Server" on extension install & vscode startup

### ISSUE THREAD

**Issue by derekantrican** [richterger/Perl-LanguageServer#10]
VSCode version:

![image](https://user-images.githubusercontent.com/1558019/74541275-310bce00-4ef6-11ea-9d80-eb126042811a.png)

Message:

![image](https://user-images.githubusercontent.com/1558019/74541327-47b22500-4ef6-11ea-84e1-61aef5422c8b.png)

**Comment by derekantrican** [comment]
Here's the output from the Developer console:

```
console.ts:137 [Extension Host] extension "perl" is now active
console.ts:137 [Extension Host] cmd: perl args: -MPerl::LanguageServer -e Perl::LanguageServer::run -- --port 13603 --log-level 0 --version 2.0.1
notificationsAlerts.ts:40 Couldn't start client Perl Language Server
onDidNotificationChange @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:582
addNotification @ notifications.ts:171
notify @ notificationService.ts:101
(anonymous) @ mainThreadMessageService.ts:83
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:582
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:582
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
log.ts:197   ERR spawn perl ENOENT: Error: spawn perl ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:9)
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Launching server using command perl failed.
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:582
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:582
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
log.ts:197   ERR Launching server using command perl failed.
```

**Comment by richterger** [comment]
Did you install Perl::LanguageServer on your system where you want to debug?



If yes, could you please run the perl with the arguments shown on the second 
line, what is the output?



Von: Derek Antrican [mailto:notifications@github.com]
Gesendet: Freitag, 14. Februar 2020 16:05
An: richterger/Perl-LanguageServer <Perl-LanguageServer@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [richterger/Perl-LanguageServer] Getting "couldn't start client 
Perl Language Server" on extension install & vscode startup (#10)



Here's the output from the Developer console:

console.ts:137 [Extension Host] extension "perl" is now active
console.ts:137 [Extension Host] cmd: perl args: -MPerl::LanguageServer -e 
Perl::LanguageServer::run -- --port 13603 --log-level 0 --version 2.0.1
notificationsAlerts.ts:40 Couldn't start client Perl Language Server
onDidNotificationChange @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:582
addNotification @ notifications.ts:171
notify @ notificationService.ts:101
(anonymous) @ mainThreadMessageService.ts:83
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:582
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:582
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
log.ts:197   ERR spawn perl ENOENT: Error: spawn perl ENOENT
        at Process.ChildProcess._handle.onexit 
(internal/child_process.js:264:19)
        at onErrorNT (internal/child_process.js:456:16)
        at processTicksAndRejections (internal/process/task_queues.js:84:9)
console.ts:137 [Extension Host] rejected promise not handled within 1 
second: Launching server using command perl failed.
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:582
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:582
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
log.ts:197   ERR Launching server using command perl failed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub 
<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Frichterger%2FPerl-LanguageServer%2Fissues%2F10%3Femail_source%3Dnotifications%26email_token%3DAAS25Z22FCXDUBF4AEUIFODRC2XKXA5CNFSM4KVJRYMKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELZKETY%23issuecomment-586326607&e=09b421e4&h=aff0477c&f=y&p=y> 
, or unsubscribe 
<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAS25Z5AQAAQP4XG3OCWADTRC2XKXANCNFSM4KVJRYMA&e=09b421e4&h=b3645371&f=y&p=y> 
.


-- 
This message has been checked by Libraesva ESG and is found to be clean.
Mark it as spam 
<http://srvmailgw3.i.ecos.de/cgi-bin/learn-msg.cgi?id=D736041926.AE20A>
Blacklist sender 
<http://srvmailgw3.i.ecos.de/cgi-bin/learn-msg.cgi?blacklist=1&id=D736041926.AE20A>

**Comment by derekantrican** [comment]
No - where do I install that from?

**Comment by richterger** [comment]
This is a Perl module. You need to install it, to get the LanguageServer extention working. Install it with

cpan Perl::LanguageServer

**Comment by beltaurus** [comment]
I struggled a bit with the installation of the Perl::Language server as well (on my WSL Ubuntu 18.04 terminal).
I was trying an install with cpan, but that kept hanging in different locations (probably the canaries asking for information). So I was successful by finally:

1. Installing a couple of missing development libraries (since I develop on WSL all the time, I was surprised that those weren't in my C++ development environment already).
2. Switching from cpan to cpanm (not sure why this helped, but it did).

Required libraries:
```
sudo apt install libdb-dev
sudo apt install libssl-dev
sudo apt install liblzma-dev
sudo apt install libperl-dev
```

Installation of Perl::LanguageServer:
```
sudo apt install cpanminus
sudo cpanm --interactive --installdeps --notest Perl::Language Server
```
This gets the Language Server up and running upon the saving of my perl scripts and modules...

My IDE is a minor patch behind the Module, but that doesn't seem to matter:
![image](https://user-images.githubusercontent.com/54114043/78408805-eb49b880-75bc-11ea-912c-82a0eb9d77c1.png)

**Comment by richterger** [comment]
The version mismatch of 2.0.1 vs. 2.0.2 is a bug and will be fixed in the next release
