### ISSUE TITLE
Hackathons in 2022

### ISSUE THREAD

**Issue by djzort** [richterger/Perl-LanguageServer#124]
I am uncertain what the best contact is for Perl-LanguageServer so I just thought i would create an issue.

We in the perl marketing committee would like to get this project involved in an IDE Hackathon in 2022 (see https://news.perlfoundation.org/post/hackothon-events-planning-2022)

Please comment on the above post and/or jump in to the marketing channel on The Perl Foundations Slack instance (perlfoundation dot slack dot com)

**Comment by richterger** [comment]
I would be happy if the Perl Language Server can be part of Hackathon and will support/participate it. I am always happy about every contribution/help to improve the Language Server, since this is a spare time project and my spare time is very limitied. Let me know what needs to be done/can be done from my side. Regards Gerald
