### ISSUE TITLE
Is there a conflict for the same user with different VS Code sessions?

### ISSUE THREAD

**Issue by beltaurus** [richterger/Perl-LanguageServer#46]
I have a situation where I often have multiple debugging sessions open, and complicated workspaces (with up to 2000 Perl files and modules).

More often than not does the LanguageServer keep crashing after parsing 100 files...
At first, I thought it was because I had multiple sessions open at the same time...
But I have the same problem if I run one session, close it, and then run a different session (with a different workspace).

Then I started assigning a different `perl.debugAdapterPort` to all my workspaces.
That seems to resolve my issue.

I will report more as I experience more, but is this expected behavior? If so, it should be documented...

**Comment by richterger** [comment]
You need an unique debugAdapterPort if you have multiple workspaces open on the same machine. This is also true if multiple users are working on the same machine, because than a LanguageServer process is started for every workspace and for every user and every LanguageServer process needs a unique debugAdapaterPort.

If you have a single workspace, you can start as much concurrent debug session as you like.
