### ISSUE TITLE
Open command

### ISSUE THREAD

**Issue by afitz-gmu** [richterger/Perl-LanguageServer#49]
Hi, 
I am trying to open a file within my perl command but I'm getting an error telling me it can't open the file. Is this supported in your perl language extension? I've used identical code in other IDE's and it opens. This is my line of code:
open(INFILE, $filename) or die "Can't open $filename\n";

**Comment by beltaurus** [comment]
Following the Perl Best Practices, I would write this as follows:
```
open my $ifh, '<', $filename or croak "$OS_ERROR\n";
```

- Don't use barewords for handles
- Don't use parenthesis for built-ins
- Don't use two-parameter style open statement
- If you insist, you should not omit the direction (read or write...)
- Don't use `die` where you need context
- Provide error messages with the maximum information
- ...

Anyway, even when violating all those style rules, the open command should work in the debugger, if the file exists.
So what is going wrong? **Your `$OS_ERROR` will tell**, but my suspicion is that `$filename` doesn't resolve in your work directory, or you don't have read permission for it?
But if you claim that it opens in other IDE's, then the culprit is most probably the work directory (where you're running the Perl application).

**Comment by richterger** [comment]
This is a Perl programming issue and has nothing to do with Perl LanguageServer/Debugger. Everything that works within Perl will work in the debugger.
