### ISSUE TITLE
Using with neovim+deoplete+LanguageClient-neovim

### ISSUE THREAD

**Issue by ggouss** [richterger/Perl-LanguageServer#67]
while I was trying to use Perl-LanguageServer as completion source for deoplete, I stuck with the following error
```
      "message" : "Unknow perlmethod _rpcreq_completion at /usr/share/perl5/site_perl/Perl/LanguageServer.pm line 217.\
```
Full log from server, which was started with command 
```
> perl -MPerl::LanguageServer -e 'Perl::LanguageServer::run' -- --debug --port 9090
```
is here: [languageserver.log](https://gist.github.com/ggouss/bf026d73f11a5bcd722d811394a507a4)

where should I investigate further?

**Comment by richterger** [comment]
That’s not an issue, that just mean that completion is not implemented 
(yet). All feature mentioned in the REAME will work, regardless of this 
message.





Von: Gregg [mailto:notifications@github.com]
Gesendet: Montag, 4. Januar 2021 17:50
An: richterger/Perl-LanguageServer <Perl-LanguageServer@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [richterger/Perl-LanguageServer] Using with 
neovim+deoplete+LanguageClient-neovim (#67)



while I was trying to use Perl-LanguageServer as completion source for 
deoplete, I stuck with the following error

      "message" : "Unknow perlmethod _rpcreq_completion at 
/usr/share/perl5/site_perl/Perl/LanguageServer.pm line 217.\

Full log from server, which was started with command

> perl -MPerl::LanguageServer -e 
> 'Perl::LanguageServer::run' -- --debug --port 9090

is here: languageserver.log 
<https://urlsand.esvalabs.com/?u=http%3A%2F%2Fgist.github.com%2Fggouss%2Fbf026d73f11a5bcd722d811394a507a4&e=09b421e4&h=88efe539&f=y&p=y>

where should I investigate further?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub 
<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Frichterger%2FPerl-LanguageServer%2Fissues%2F67&e=09b421e4&h=aa5f44ea&f=y&p=y> 
, or unsubscribe 
<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAS25Z77QY4UT3ZUZD55SDTSYHWRVANCNFSM4VTIRJIA&e=09b421e4&h=84ab5e38&f=y&p=y> 
.


-- 
This message has been checked by Libraesva ESG and is found to be clean.
Mark it as spam <https://avgw.i.ecos.de/action/DBCE541D69.A11C3/learn-spam>
Blacklist sender 
<https://avgw.i.ecos.de/cgi-bin/learn-msg.cgi?blacklist=1&id=DBCE541D69.A11C3>
